# NUMPY

# to installnumoy er can make use of the method of 

In [1]:
! pip install numpy


[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np 
# creating an 1d array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# 1d array has an single   [] bracket

[1 2 3 4 5]


In [ ]:
# to reshapre and 1d array to 2d arary 
arra2 = np.array([1, 2, 3, 4, 5, 6])
arra2.reshape(1,6) # reshaping to 1 row and 5 columns

# here in the output we can see that there are 2 [] brackets which means it is a 2d array
[[1, 2, 3, 4, 5, 6]])

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
# 2 dimension array 2 times iti s openneing an 2 times it is closing  [[]]
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)
print(arr3.shape) # 2,3  indicates 2 rows and 3 columns

[[1 2 3]
 [4 5 6]]
(2, 3)


In [12]:
np.arange(0, 10, 2)  # it will generate numbers from 0 to 10 with a step of 2

array([0, 2, 4, 6, 8])

In [ ]:
Use Case	Why use np.ones()?
Initialize weight matrices in ML	start with identical values
Create masks	1 = include, 0 = exclude
Quickly create test data	easy and clean
Fill arrays before updating	placeholder values

In [15]:
# np.ones

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# identity matrix
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#  attritibutes of Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape) # Output: (2, 3)
print("Number of dimensions:", arr.ndim) # Output: 2
print("Size (number of elements):", arr.size) # Output: 6
print("Data type:", arr.dtype) # Output: int64.(may.vary.based.on.platform)
print("Item size (in bytes):", arr.itemsize) # Output: 8 (may vary based on os

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [ ]:
# numpy vectorize operation 
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# addition  operation 
print("addition:" , arr1 + arr2)

# sub 
print("sub : " , arr1 - arr2)

# div 

print("div:", arr1 / arr2) 
 # in mumpy every numpy operation provide the same class 

addition: [11 22 33 44 55]
sub :  [ -9 -18 -27 -36 -45]
div: [0.1 0.1 0.1 0.1 0.1]


In [21]:
# univeral Function , func tha applies to the entire function 
# these are performed as ----np.fun------\\\


arr = np.array([1,2,3,4,5])

#square root 
print(np.sqrt(arr))

# ecponwntinal 

print(np.exp(arr))

# sine 

print(np.sin(arr))


# log 

print(np.log(arr))


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [25]:
# array slicing and indexing operation 

# creating an 2d array 
arr = np.array([[1,2,3,4] , [5,6,7,8] , [ 9 , 10 , 11, 12 ]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr[0] # acces the row 

array([1, 2, 3, 4])

In [27]:
arr[0][0] # scess therow and thecol 

np.int64(1)

In [31]:
# to acces the  eleet at the second row and the third col 
arr[1][2]

np.int64(7)

In [33]:
# printing  / getting the speccific row and column 

arr[1:] # print the row after the "1" rows 

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr[1:,2:]  # lecving the frist row and 2 colums 

array([[ 7,  8],
       [11, 12]])

In [46]:
# to get the 2x2  matric 

arr[0:2 , 2: ]

array([[3, 4],
       [7, 8]])

In [ ]:
arr[1:3 , 1 : 3 ] # before index "3 " we will get the calvue s before three 

array([[ 6,  7],
       [10, 11]])

In [50]:
# modifyinhht array elemets 
arr[0][0] = 99
print(arr)

[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [51]:
# replacing the elemts from all the roes except 1st 
arr[1:] = 100 
print(arr)

[[ 99   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [52]:
# stastical concept -- normalization 
# to have mean 0 and standard deviation 1

data = np.array([1,2,3,4,5])


# calculation 
mean = np.mean(data)
std = np.std(data)

# 
# normalaization 

nor  = (data - mean) / (std)
print('nor' , nor)

nor [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [56]:
# logixal operations 

data = np.array([1,2,3,4,5 ,6,7,8,9])

data>5 

# to get eh elemets greater tan 5 we will make use of the indexng 

data[data>5]

array([6, 7, 8, 9])